### ISSUE TITLE
Controller Location wrong

### ISSUE THREAD

**Issue by stbabu** [NOLOVR/NOLO-Driver-For-Windows#10]
I have one controller that always shows up about 10 feet behind me in applications. It does this in the Nolo Tetris app as well as any Steam app. I've tried re-pairing, double-clicking, pressing the button on the head marker, etc, nothing makes the second controller show up properly. Both controllers are tracked, BTW, just one shows up in the wrong location.

I'm on Windows 10 x64.

**Comment by Hettylool** [comment]
@stbabu 

How about the Visualizer?
the location wrong controller has rotation and button is work?

**Comment by stbabu** [comment]
In the visualizer, the controller is still in the wrong location.  The
rotation and buttons work, it just appears to be about 10 feet behind me.

On Jul 3, 2017 11:15 PM, "Test" <notifications@github.com> wrote:

@stbabu <https://github.com/stbabu>

How about the Visualizer?
the location wrong controller has rotation and button is work?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NOLOVR/NOLO-Driver-For-Windows/issues/10#issuecomment-312770693>,
or mute the thread
