### ISSUE TITLE
Proximity Sensor Emulation

### ISSUE THREAD

**Issue by Wully616** [NOLOVR/NOLO-Driver-For-Windows#12]
Within some games, they make use of the proximity sensor in the Oculus Rift or Vive.
One example is RecRoom, when playing the game, it detects you are "inactive" and kicks you after 30 seconds.

I've asked the RecRoom devs about this, their reply was that it could be the Nolo driver not sending presence of a sensor or at least, is not emulating one when the player is moving. https://www.reddit.com/r/RecRoom/comments/6k4dzp/constantly_being_kicked_for_inactivity/

**Comment by Hettylool** [comment]
@Wully616 
Hi
our team is going to figure it out.
