### ISSUE TITLE
Mounting base station at an angle

### ISSUE THREAD

**Issue by Wully616** [NOLOVR/NOLO-Driver-For-Windows#13]
Is it possible to add an enhancement so we can mount the base station at an angle.
I would like to mount it in the top corner of the room so it faces down into the centre of the play area.

Right now when I try it the movement is exaggerated along the Y axis when I move the controller or head set around. 

Is there a gyroscope built into the base station?
 Can you programmatically determine what angle its sitting at and adjust the depth calculations based on that?

**Comment by TristanBurnside** [comment]
I'd also like to see this.

Probably the best way to implement it would be to note the direction that the HMD is facing relative to the base station when it is reset (by placing it on the floor and pushing the button) and use that to adjust the calculations. It already looks like this adjusts height.

**Comment by Tux0Topo** [comment]
This would give us a lot of advantages for better tracking space....

There are ways to define the rotation on the base.
The base itself have some type of orientation (don't know if it's enough). Other way could be by using some know mat for calibration (similar to the psmove service), to calculate the transformation from tracking vs position....

Anyways, i'm more worried about the power control of the base... There is no native remote/software power switch for it....

**Comment by LyuzhouZ** [comment]
We'll consider adding this functionality in the next version.
