### ISSUE TITLE
Ability to bind 180 rotation to a different button or multiple buttons

### ISSUE THREAD

**Issue by Wully616** [NOLOVR/NOLO-Driver-For-Windows#14]
There are loads of games which use the application button to drop items, open menus etc
Sometimes having to double press the application button to flip around breaks the games immersion.

One example is modbox. I can't hold two guns and rotate around 180 because I'll drop one of them.

In a lot of games both grip buttons are used for the same thing, locomotion or picking something up.
I hope both grip buttons on each controller are detected individually so I could use one of them!

Can you add in the ability to change the rotate 180 button to a different button

**Comment by POEDaley** [comment]
I had the same issue as Wully.  In Out of Ammo I found that the application button while in a tower or bunker will make you exit it upon the first press.  So while trying to be a sniper in a tower you can't use the 180 feature either.  I'm sure there are plenty of other games that will be affected as well.

If you could just have some sort of toggle in the driver, that would be fantastic.  So perhaps having the option between double tapping the touchpad/application menu/grip would give us much more freedom. 

Thanks.

**Comment by Hettylool** [comment]
ok,i got it.

**Comment by TheDeveloperGuy** [comment]
@Hettylool I don't think this should be a function of the runtime, and it should be a decision of the app/driver to give this functionality. At least there should be a way to disable it. I accidentally pressed it when I was testing my driver in SteamVR and couldn't figure out why suddenly the Z values were reversed. 😆

**Comment by LyuzhouZ** [comment]
Fixed
