### ISSUE TITLE
no haptic feedback from controllers

### ISSUE THREAD

**Issue by belly1912** [NOLOVR/NOLO-Driver-For-Windows#15]
my controllers vibrate when they are turned on, so i know the motors are working, but i don't get feedback in games. one example would be when you pull back the bow in the Lab, i know this is supposed to give feedback as i have it on the Vive. any suggestions or fixes?

**Comment by Hettylool** [comment]
is still not get feedback ?

**Comment by belly1912** [comment]
Still no haptic feedback or suggestions or help or acknowledgement or hope.....

**Comment by Hettylool** [comment]
@belly1912  uninstall old nolo and install it again,make sure the all file is replace,and try it again.

**Comment by belly1912** [comment]
I have tried every driver available except 0.8  and none of them made any difference to the feedback..

**Comment by POEDaley** [comment]
In your steamvr.vrsettings file, do you a flag for "rumble_suppressed".  I know that flag works with PS move, but unsure about Nolo.  If it's there, try setting it to : false

**Comment by belly1912** [comment]
i would imagine that everyone else would have the same problem, which they don't seem to.. but thanks anyway, I'll take a look.

**Comment by Hettylool** [comment]
i will give you a test exe tomorrow.to test if the feedback if work.you can tell me your email.

**Comment by belly1912** [comment]
My email is grahambell1912@gmail.com 
Thanks

**Comment by belly1912** [comment]
Hi 
I have tried it and unfortunately i get no feedback, for about every 5 presses of the trigger i might get a very very tiny movement in the motor maybe 5 milliseconds worth..

please advise?

**Comment by belly1912** [comment]
the problem was that the cable was connected to a usb 2 port and not a usb 3 port.. with usb 3 it works fine.
