### ISSUE TITLE
How to play Oculus games with sensor check : Chronos, Landfall, Edge of Nowhere... ??

### ISSUE THREAD

**Issue by Djneo134** [NOLOVR/NOLO-Driver-For-Windows#18]
Hi,
I've tried everything but since I have installed my Nolo system, every games from oculus library which check sensors at the beginning don't work now.

I use Steam VR, Revive, Riftcat, Samsung Galaxy s8 and Homido v2.

Before Nolo, PSMoveService and a PSEye webcam did the trick but now, with Nolo driver installed, every games like Chronos, Landfall, Edge of Nowhere, Herobound : Spirit Champion... aren't playable. They all check if oculus sensor and headset are connected before accessing the Menu.

Is there a way to play these games with Revive, Riftcat and Nolo ?

Thanks a lot.

**Comment by Hettylool** [comment]
i will check,you know it is difficult to connect the oculus home in china.

**Comment by Djneo134** [comment]
The best'ld be to emulate the hmd and the oculus sensor so that all these games think we are using a regular oculus rift and not another unknown system (for oculus home) like Nolo.

**Comment by duig0** [comment]
In riftcat settings (on pc) you cab enable Fake Sensor.

This allowed me to play Wilsons heart without issue

**Comment by Djneo134** [comment]
Maybe this one but no other can be launch with the Fake sensor option in Riftcat.
Neither Landfall, nor the Mage's Tale, nor Chronos, nor Edge of Nowhere...

**Comment by duig0** [comment]
I have tried Edge of nowhere and you are right...
However, i have a work around.

Use Trinus vr, instead of riftcat

Use psmoveservice with a pseye cam 

And it works as before.

I had to reinstall the psmoveservice steamvr driver after installing nolo driver.

Doesnt work with riftcat but works fine with trinusvr

**Comment by LyuzhouZ** [comment]
If RiftCat doesn't work, Trinus+Revive is our recommended solution.
