### ISSUE TITLE
The touch pad triggers by itself

### ISSUE THREAD

**Issue by isketch93** [NOLOVR/NOLO-Driver-For-Windows#20]
Like the title says, one of my controller triggers the touch pad by itself, mostly on the top side, but occasionally it will tap to the left or to the right. Putting my thumb down on the pad makes a little difference, as the registered position moves rapidly between where I'm holding my thumb and where the auto-triggering happens. 

This issue does not affect the few android games like Tetris since they do not use the pad in any way, I noticed this when I jumped on steamvr, where random actions like screenshots began to trigger apparently by themselves. Only looking down at the controllers showed me that one was registering ghost touches on the pad. The controller calibration included in steamvr does not affect this behaviour in any noticeable way.

I've seen other people report this issues on the forums and on Reddit. Would it be possible to solve this problem through the drivers? Maybe lowering the sensitivity of the touchpad, or something like that.

**Comment by POEDaley** [comment]
I have noticed this as well.  In a game I opened up just the other night, it was as if I was holding the left side.  If I pressed the right side, the right side would trigger and I would move to the right.  But as soon as I let go, I would go left again.  This could easily be solved perhaps by opening up the dead zone in the center a little bit.

**Comment by rodferris** [comment]
I can confirm this is an issue.  Google Earth demonstrates this very well.  I have to compensate by holding down the touchpad in the opposite direction.  This is by far the biggest annoyance for me.

**Comment by nanospork** [comment]
I've also had this occur. I'm using the Nolo-OSVR driver with an unreleased version of SteamVR-OSVR though, which indicates that it is probably a hardware/firmware issue and not a driver issue.

**Comment by nravanelli** [comment]
I have the exact same issue in Arizona Sunshine and Dead Effect 2 VR. You cannot use the directional pads for movement since I am constantly moving backwards... However, this seems to work just fine in Pavlov VR which requires directional pad movements. This lends me to think this might be a firmware/input issue.

**Comment by Aqas** [comment]
I have a similar problem too. In most situations the touch pads are not centered. The default (touching) position of the pad sits in the bottom left corner of the pad. This leads to walking backwards, if touch pad movement are used. I'm using steamvr with osvr hdk2 goggles. A configuration tool to calibrate the pads would make sense.

**Comment by Hettylool** [comment]
@isketch93 @POEDaley @rod78 @nanospork @nravanelli @Aqas 
i got it,and i will check it.

**Comment by MykeyRM** [comment]
same issue for me scrolling through menus on its own. and keeping my thump in the center position is a real struggle.

**Comment by belly1912** [comment]
I also have the same problem when i play Pavlov

**Comment by duig0** [comment]
Any updates on this? Nolo is almost unusable for me (as i only seem to have the effected games in my libary....lol)

**Comment by LyuzhouZ** [comment]
Fixed.
