### ISSUE TITLE
Memory leak in new update.

### ISSUE THREAD

**Issue by booty156** [NOLOVR/NOLO-Driver-For-Windows#4]
Memory increases within a few hours when left running

**Comment by booty156** [comment]
Quote from Richard Martin 2 days ago
'The latest beta driver did fix the high CPU usage issue, but there's still a memory leak in there.
After sitting in the background doing nothing for 6 hours, the driver was using a 729mb footprint on my PC. (From the 18 mb it uses on starting up)
http://i.imgur.com/V7xfCmV.png'

**Comment by Hettylool** [comment]
we are try to find out.

**Comment by LyuzhouZ** [comment]
Fixed
