### ISSUE TITLE
win10+Nolo_driver_for_windows_setup_0.3.0_beta.msi_not boot driver&tool

### ISSUE THREAD

**Issue by Michael4465** [NOLOVR/NOLO-Driver-For-Windows#6]
Nolo_driver_for_windows_setup_0.3.0_beta.msi
install
click on "NOLO".
"NOLO-Driver-For-Windows will run minimize to the tray."
but. not boot NOLO tools or Driver.
please fix installer

**Comment by edzuantengku** [comment]
i have the same problem...
the nolo tool does not pop on the taskbar.

**Comment by edzuantengku** [comment]
![nolo driver](https://user-images.githubusercontent.com/21078303/27088484-5e7319b0-508a-11e7-8473-69da111f01bd.png)
see image.. no NOLO tool after driver install

**Comment by booty156** [comment]
Same

**Comment by edzuantengku** [comment]
Fyi.. i'm running on win 10.

**Comment by Michael4465** [comment]
0.3.1 is works

**Comment by booty156** [comment]
Nope still not working. Was using the latest update anyway

**Comment by POEDaley** [comment]
Using 0.3.1 on Windows 10, and I can confirm it's not working for me either.
