### ISSUE TITLE
Controller not work @ SteamVR

### ISSUE THREAD

**Issue by jacklai4dev** [NOLOVR/NOLO-Driver-For-Windows#7]
Step:
1. Connect HeadMarker to PC
2. Pair 2 controllers and headset marker to base station
3. Launch Nolo Driver Tools
4. All Devices connected.
5. Open Riftcat
6. Connect to mobile phone
7. Press "Play Steam VR"

Result:
1. SteamVR cannot detect controller 1+2
 (Head Marker and Base Station are connected to SteamVR)

**Comment by Michael4465** [comment]
I also have the same problem..hmm

**Comment by GXiaoyang** [comment]
I would like to know you use the NOLO PC software version number, and steamvr.vrsettings file steamvr configuration whether there is "activateMultipleDrivers: true", if not please try

**Comment by Michael4465** [comment]
now using 0.4.0 + win10 pro x64

>steamvr.vrsettings file steamvr configuration whether there is "activateMultipleDrivers: true
I have used this method from a long time ago.
------------------------------------------------------------------------------------------------
my NOLO do not recognize the controller.

1.base station power ON
2.push the few sec base station 'Pairing button' to flash to base station "power button"
3.1+2 controller & HDM sencer? push to few sec RED flash
4.push to base station 'Pairing button' 1+2 controller & HDM sencer? green light ON

but NOLO tools
BaseStation:Connected
ControllerOne:NoConnect
ControllerTwo:NoConnect

:(

**Comment by Hettylool** [comment]
@Michael4465  controller & hmd sencer should be green light Long bright，If it still don't recognize the controller. try to Restart all devices and driver.

**Comment by Michael4465** [comment]
PC restart & all driver uninstall & install.
rePairing is work.

Hmd:Connect
BaseStation:Connect
ControllerOne:Connect
ControllerTwo:Connect

but SteamVR is new update. not work GerVR lol omg.

**Comment by jacklai4dev** [comment]
work with 0.4.0_beta
