### ISSUE TITLE
head tracker problem on windows7 Ultimate 64bit

### ISSUE THREAD

**Issue by chrisx2ds** [NOLOVR/NOLO-Driver-For-Windows#8]
By using the same cable, windows 7 was able to detect and install driver for each device(controller and base station) except the head tracker, windows7 cannot detect or recognize it, so windows cannot auto install the necessary file.  

 P.S.   I have try on my laptop with windows 10, and everything just work grate.

**Comment by Hettylool** [comment]
@chrisx2ds 
hi
some win7 have this problem.
there is method to solve this question with a usb hub.
1.Connect the usb hub to the power supply.
2.plug nolo in usb hub 
3.plug usb hub in computer
with this step can solve this question.
