### ISSUE TITLE
Head Tracking orientation issue

### ISSUE THREAD

**Issue by Kibbols** [NOLOVR/NOLO-Driver-For-Windows#9]
My nolo's L shaped mount arrived with a very weak adhesive on it, but the flat mount was very strong. I had to use the flat mount on the front of my headset (mergeVR can't do the top). This meant instead of pointing upwards, the HDM was pointing outwards. Although it worked fine after syncing. All of a sudden this setup doesn't seem to be working. I've changed nothing, but it's making me stare constantly at the floor.

EDIT: this seems to only be an issue on windows for me. playing the tetris game on Android worked perfectly.

**Comment by Hettylool** [comment]
@Kibbols  
hi,
if you play steamvr with riftcat,you can choose Gear VR in nolo driver for windows,if you play with trinus,i think you should take the nolo's L shaped mount down,and Paste it again.
We recommend that Paste it again.

**Comment by Kibbols** [comment]
@Hettylool I used some double sided tape to attach it to the headset, but it still falls off.

**Comment by Hettylool** [comment]
@Kibbols  
hi 
Can you buy a 3M double sided tape？
we use 3M double sided tape.and i will give your trouble to back to my team.

**Comment by stbabu** [comment]
I have one controller that always shows up about 10 feet behind me in applications.  It does this in the Nolo Tetris app as well as any Steam app.  I've tried re-pairing, double-clicking, pressing the button on the head marker, etc, nothing makes the second controller show up properly. Both controllers are tracked, BTW, just one shows up in the wrong location.
